// This file was generated by json2swift. https://github.com/ijoshsmith/json2swift

import Foundation

struct User: CreatableFromJSON { // TODO: Rename this struct
    let data: Data
    let message: String
    let success: Bool
    init(data: Data, message: String, success: Bool) {
        self.data = data
        self.message = message
        self.success = success
    }
    init?(json: [String: Any]) {
        guard let data = Data(json: json, key: "Data") else { return nil }
        guard let message = json["Message"] as? String else { return nil }
        guard let success = json["Success"] as? Bool else { return nil }
        self.init(data: data, message: message, success: success)
    }
    struct Data: CreatableFromJSON { // TODO: Rename this struct
        let address: String
        let deviceToken: String
        let deviceType: String
        let latitude: String
        let longitude: String
        let password: Any?
        let userID: Int
        let userName: String
        init(address: String, deviceToken: String, deviceType: String, latitude: String, longitude: String, password: Any?, userID: Int, userName: String) {
            self.address = address
            self.deviceToken = deviceToken
            self.deviceType = deviceType
            self.latitude = latitude
            self.longitude = longitude
            self.password = password
            self.userID = userID
            self.userName = userName
        }
        init?(json: [String: Any]) {
            guard let address = json["Address"] as? String else { return nil }
            guard let deviceToken = json["DeviceToken"] as? String else { return nil }
            guard let deviceType = json["DeviceType"] as? String else { return nil }
            guard let latitude = json["Latitude"] as? String else { return nil }
            guard let longitude = json["Longitude"] as? String else { return nil }
            guard let userID = json["UserID"] as? Int else { return nil }
            guard let userName = json["UserName"] as? String else { return nil }
            let password = json["Password"] as? Any
            self.init(address: address, deviceToken: deviceToken, deviceType: deviceType, latitude: latitude, longitude: longitude, password: password, userID: userID, userName: userName)
        }
    }
}
